Synchronize lcs-sftp init script with wheezy's ssh init script.

diff --git a/lcs-preinstall/debian/lcs-preinstall.lcs-sftp.init b/lcs-preinstall/debian/lcs-preinstall.lcs-sftp.init
--- a/lcs-preinstall/debian/lcs-preinstall.lcs-sftp.init
+++ b/lcs-preinstall/debian/lcs-preinstall.lcs-sftp.init
@@ -37,10 +37,10 @@ check_for_no_start() {
     # forget it if we're trying to start, and /etc/ssh/sshd_not_to_be_run exists
     if [ -e /etc/ssh/sshd_not_to_be_run ]; then 
 	if [ "$1" = log_end_msg ]; then
-	    log_end_msg 0
+	    log_end_msg 0 || true
 	fi
 	if ! run_by_init; then
-	    log_action_msg "LCS SFTP OpenBSD Secure Shell server not in use (/etc/ssh/sshd_not_to_be_run)"
+	    log_action_msg "LCS SFTP OpenBSD Secure Shell server not in use (/etc/ssh/sshd_not_to_be_run)" || true
 	fi
 	exit 0
     fi
@@ -52,7 +52,7 @@ check_dev_null() {
 	    log_end_msg 1 || true
 	fi
 	if ! run_by_init; then
-	    log_action_msg "/dev/null is not a character device!"
+	    log_action_msg "/dev/null is not a character device!" || true
 	fi
 	exit 1
     fi
@@ -79,75 +79,73 @@ case "$1" in
 	check_privsep_dir
 	check_for_no_start
 	check_dev_null
-	log_daemon_msg "Starting OpenBSD Secure Shell server" "lcs-sftp"
+	log_daemon_msg "Starting OpenBSD Secure Shell server" "lcs-sftp" || true
 	if start-stop-daemon --start --quiet --oknodo --pidfile /var/run/lcs-sftp.pid --exec /usr/sbin/sshd -- $SSHD_OPTS; then
-	    log_end_msg 0
+	    log_end_msg 0 || true
 	else
-	    log_end_msg 1
+	    log_end_msg 1 || true
 	fi
 	;;
   stop)
 	log_daemon_msg "Stopping OpenBSD Secure Shell server" "lcs-sftp"
 	if start-stop-daemon --stop --quiet --oknodo --pidfile /var/run/lcs-sftp.pid; then
-	    log_end_msg 0
+	    log_end_msg 0 || true
 	else
-	    log_end_msg 1
+	    log_end_msg 1 || true
 	fi
 	;;
 
   reload|force-reload)
 	check_for_no_start
 	check_config
-	log_daemon_msg "Reloading OpenBSD Secure Shell server's configuration" "lcs-sftp"
+	log_daemon_msg "Reloading OpenBSD Secure Shell server's configuration" "lcs-sftp" || true
 	if start-stop-daemon --stop --signal 1 --quiet --oknodo --pidfile /var/run/lcs-sftp.pid --exec /usr/sbin/sshd; then
-	    log_end_msg 0
+	    log_end_msg 0 || true
 	else
-	    log_end_msg 1
+	    log_end_msg 1 || true
 	fi
 	;;
 
   restart)
 	check_privsep_dir
 	check_config
-	log_daemon_msg "Restarting OpenBSD Secure Shell server" "lcs-sftp"
+	log_daemon_msg "Restarting OpenBSD Secure Shell server" "lcs-sftp" || true
 	start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile /var/run/lcs-sftp.pid
 	check_for_no_start log_end_msg
 	check_dev_null log_end_msg
 	if start-stop-daemon --start --quiet --oknodo --pidfile /var/run/lcs-sftp.pid --exec /usr/sbin/sshd -- $SSHD_OPTS; then
-	    log_end_msg 0
+	    log_end_msg 0 || true
 	else
-	    log_end_msg 1
+	    log_end_msg 1 || true
 	fi
 	;;
 
   try-restart)
 	check_privsep_dir
 	check_config
-	log_daemon_msg "Restarting OpenBSD Secure Shell server" "lcs-sftp"
-	set +e
-	start-stop-daemon --stop --quiet --retry 30 --pidfile /var/run/lcs-sftp.pid
-	RET="$?"
-	set -e
+	log_daemon_msg "Restarting OpenBSD Secure Shell server" "lcs-sftp" || true
+	RET=0
+	start-stop-daemon --stop --quiet --retry 30 --pidfile /var/run/lcs-sftp.pid || RET="$?"
 	case $RET in
 	    0)
 		# old daemon stopped
 		check_for_no_start log_end_msg
 		check_dev_null log_end_msg
 		if start-stop-daemon --start --quiet --oknodo --pidfile /var/run/lcs-sftp.pid --exec /usr/sbin/sshd -- $SSHD_OPTS; then
-		    log_end_msg 0
+		    log_end_msg 0 || true
 		else
-		    log_end_msg 1
+		    log_end_msg 1 || true
 		fi
 		;;
 	    1)
 		# daemon not running
-		log_progress_msg "(not running)"
-		log_end_msg 0
+		log_progress_msg "(not running)" || true
+		log_end_msg 0 || true
 		;;
 	    *)
 		# failed to stop
-		log_progress_msg "(failed to stop)"
-		log_end_msg 1
+		log_progress_msg "(failed to stop)" || true
+		log_end_msg 1 || true
 		;;
 	esac
 	;;
