Fix maintainer scripts to not use absolute path when calling programs
dpkg ensures the maintainers scripts have a sane PATH which includes
the usual /bin, /sbin, /usr/bin, /usr/sbin and as such it's harmful
to include the full path as it makes it impossible to move the program
to some other place (while still staying in the PATH).

This fixes the corresponding lintian warnings:
W: lcs-apache2ssl: command-with-path-in-maintainer-script postinst:21 /usr/bin/mysql
W: lcs-apache2ssl: command-with-path-in-maintainer-script postinst:24 /usr/bin/mysql
W: lcs-apache2ssl: command-with-path-in-maintainer-script postinst:26 /usr/bin/mysql
W: lcs-apache2ssl: command-with-path-in-maintainer-script postinst:74 /usr/sbin/lcs-make-sudoers
W: lcs-apache2ssl: command-with-path-in-maintainer-script postrm:35 /usr/sbin/lcs-make-sudoers
W: lcs-preinstall: command-with-path-in-maintainer-script prerm:23 /usr/sbin/lcs-remove-sudoers
W: lcs-security: command-with-path-in-maintainer-script postinst:60 /usr/sbin/lcs-make-sudoers
W: lcs-security: command-with-path-in-maintainer-script postinst:63 /usr/sbin/lcs-disable-apache-security
W: lcs-security: command-with-path-in-maintainer-script postrm:29 /usr/sbin/lcs-make-sudoers

Here's the long description of the lintian warning:

W: lcs-apache2ssl: command-with-path-in-maintainer-script postinst:21 /usr/bin/mysql
N:
N:   The indicated program run in a maintainer script has a prepended path.
N:   Programs called from maintainer scripts normally should not have a
N:   path prepended. dpkg ensures that the PATH is set to a reasonable
N:   value, and prepending a path may prevent the local administrator from
N:   using a replacement version of a command for some local reason.
N:
N:   If the path is required to test a program for existence, one of the
N:   suggested workarounds in the developer's reference can be used.
N:
N:   See particularly the function pathfind() in devref.
N:
N:   Refer to Debian Policy Manual section 6.1 (Introduction to package
N:   maintainer scripts) and Debian Developer's Reference section 6.4 (Best
N:   practices for maintainer scripts) for details.
N:
N:   Severity: normal, Certainty: certain
N:
N:   Check: scripts, Type: binary
N:

diff --git a/lcs-security/debian/postinst b/lcs-security/debian/postinst
--- a/lcs-security/debian/postinst
+++ b/lcs-security/debian/postinst
@@ -47,20 +47,16 @@ EOP
 		chmod 640 /var/log/lcs/check.log
 		chown www-data:www-data /var/log/lcs/check.log
 	fi
-   # Restart fail2ban
-	if [ -x /usr/sbin/invoke-rc.d ]; then
-		invoke-rc.d fail2ban restart
-	else
-		/etc/init.d/fail2ban restart
-	fi
+	# Restart fail2ban
+	invoke-rc.d fail2ban restart || true
 	# Update sudoers lt 2.4.9.1
 	if [ -n "$2" ] && dpkg --compare-versions "$2" lt 2.4.9.1; then	
 				echo "update lcs-security and disable mod_apache_security"
 		    	# Activation des logs sudo
-		    	/usr/sbin/lcs-make-sudoers
+		    	lcs-make-sudoers
 		    	# Desactivation du mod security d'apache
 		    	echo "le mod security d'apache est disponible."
-		    	/usr/sbin/lcs-disable-apache-security 
+		    	lcs-disable-apache-security 
 	fi
 
 
